// Declares and assigns values to the constants in the game

module.exports = Object.freeze({
    MSG: {
        GAME_JOIN: 'game_join',
        GAME_UPDATE: 'game_update',
        INPUT: 'input',
        GAME_OVER: 'game_over'
    },
    MAP: {
        MIN_X: 0,
        MAX_X: 5000,
        MIN_Y: 0,
        MAX_Y: 5000
    },
    RENDER_DELAY: 100,
    DECELERATION: .995,
    KILL_SCORE: 500,
    PLAYER_RADIUS: 50,
    BULLET_RADIUS: 20,
    BULLET_VELOCITY: 1500,
    HEALTHPACK_RADIUS: 20,
    AMMOPACK_RADIUS: 20,
    AMMOPACK_CONTENT: 10,
    NUM_HEALTHPACKS: 50,
    NUM_AMMOPACKS: 50,
    HEALTHPACK_HEALTH: 10,
    BULLET_DAMAGE: 10,
    NUM_BIG_ASTEROIDS: 100,
    BIG_ASTEROID_VELOCITY: 40,
    BIG_ASTEROID_RADIUS: 100,
    BIG_ASTEROID_SCORE: 20,
    BIG_ASTEROID_HP: 50,
    BIG_ASTEROID_DAMAGE: 50,
    MEDIUM_ASTEROID_VELOCITY: 50,
    MEDIUM_ASTEROID_RADIUS: 40,
    MEDIUM_ASTEROID_SCORE: 10,
    MEDIUM_ASTEROID_HP: 20,
    MEDIUM_ASTEROID_DAMAGE: 20,
    SMALL_ASTEROID_VELOCITY: 60,
    SMALL_ASTEROID_RADIUS: 20,
    SMALL_ASTEROID_SCORE: 5,
    SMALL_ASTEROID_HP: 10,
    SMALL_ASTEROID_DAMAGE: 10,
    MAX_AMMO: 20
});
